#!/bin/sh

set -eu

unset -f install_config_alacritty_symlink
unset -f install_config_alacritty
unset -f install_config_alacritty_driver

# -----------------------------------------------------------------------------
# Make symbolic link
#
# @param {string} $1 - target
# @param {string} $2 - link
#
install_config_alacritty_symlink() {
  if [ $# -ne 2 ]; then
    msg_param_error "install_config_alacritty_symlink" "$@"
    exit 1
  fi

  local target="$1"
  local link="$2"

  msg_normal "Installing ${target##*/}"
  if ! fs_ln_s "$target" "$link"; then
    exit 1
  fi
}

# -----------------------------------------------------------------------------
# Installer
#
# @param {string} $1 - project root path
#
install_config_alacritty() {
  if [ $# -ne 1 ]; then
    msg_param_error "install_config_alacritty" "$@"
    exit 1
  fi

  local root="$1"

  local src="${root}/config/alacritty"
  local dst="${HOME}/.config/alacritty"

  if ! fs_mkdir "$dst"; then
    exit 1
  fi

  install_config_alacritty_symlink \
    "${src}/alacritty.toml" "${dst}/alacritty.toml"

  install_config_alacritty_symlink \
    "${src}/base16-eighties.toml" "${dst}/base16-eighties.toml"
}

# -----------------------------------------------------------------------------
# Driver
#
install_config_alacritty_driver() {
  local root
  root="$(realpath "$(dirname "$(realpath "$0")")/../../../")"

  . "${root}/script/lib/fs"
  . "${root}/script/lib/list"
  . "${root}/script/lib/msg"

  install_config_alacritty "$root"
}

if [ "${0##*/}" = "alacritty" ]; then
  install_config_alacritty_driver
fi
