#!/bin/sh

set -eu

unset -f install_config_dircolors_symlink
unset -f install_config_dircolors
unset -f install_config_dircolors_driver

# -----------------------------------------------------------------------------
# Make symbolic link
#
# @param {string} $1 - target
# @param {string} $2 - link
#
install_config_dircolors_symlink() {
  if [ $# -ne 2 ]; then
    msg_param_error "install_config_dircolors_symlink" "$@"
    exit 1
  fi

  local target="$1"
  local link="$2"

  msg_normal "Installing ${target##*/}"
  if ! fs_ln_s "$target" "$link"; then
    exit 1
  fi
}

# -----------------------------------------------------------------------------
# Installer
#
# @param {string} $1 - project root path
#
install_config_dircolors() {
  if [ $# -ne 1 ]; then
    msg_param_error "install_config_dircolors" "$@"
    exit 1
  fi

  local root="$1"

  local src="${root}/config/dircolors"
  local dst="${HOME}"

  install_config_dircolors_symlink "${src}/dircolors" "${dst}/.dircolors"
}

# -----------------------------------------------------------------------------
# Driver
#
install_config_dircolors_driver() {
  local root
  root="$(realpath "$(dirname "$(realpath "$0")")/../../../")"

  . "${root}/script/lib/fs"
  . "${root}/script/lib/list"
  . "${root}/script/lib/msg"

  install_config_dircolors "$root"
}

if [ "${0##*/}" = "dircolors" ]; then
  install_config_dircolors_driver
fi
