#!/bin/sh

set -eu

unset -f install_config_fontconfig_symlink
unset -f install_config_fontconfig
unset -f install_config_fontconfig_driver

# -----------------------------------------------------------------------------
# Make symbolic link
#
# @param {string} $1 - target
# @param {string} $2 - link
#
install_config_fontconfig_symlink() {
  if [ $# -ne 2 ]; then
    msg_param_error "install_config_fontconfig_symlink" "$@"
    exit 1
  fi

  local target="$1"
  local link="$2"

  msg_normal "Installing ${target##*/}"
  if ! fs_ln_s "$target" "$link"; then
    exit 1
  fi
}

# -----------------------------------------------------------------------------
# Installer
#
# @param {string} $1 - project root path
#
install_config_fontconfig() {
  if [ $# -ne 1 ]; then
    msg_param_error "install_config_fontconfig" "$@"
    exit 1
  fi

  local root="$1"

  local src="${root}/config/fontconfig"
  local dst="${HOME}/.config/fontconfig"

  if ! fs_mkdir "$dst"; then
    exit 1
  fi

  install_config_fontconfig_symlink "${src}/fonts.conf" "${dst}/fonts.conf"
}

# -----------------------------------------------------------------------------
# Driver
#
install_config_fontconfig_driver() {
  local root
  root="$(realpath "$(dirname "$(realpath "$0")")/../../../")"

  . "${root}/script/lib/fs"
  . "${root}/script/lib/list"
  . "${root}/script/lib/msg"

  install_config_fontconfig "$root"
}

if [ "${0##*/}" = "fontconfig" ]; then
  install_config_fontconfig_driver
fi
