#!/bin/sh

set -eu

unset -f install_config_vim_symlink
unset -f install_config_vim
unset -f install_config_vim_driver

# -----------------------------------------------------------------------------
# Make symbolic link
#
# @param {string} $1 - target
# @param {string} $2 - link
#
install_config_vim_symlink() {
  if [ $# -ne 2 ]; then
    msg_param_error "install_config_vim_symlink" "$@"
    exit 1
  fi

  local target="$1"
  local link="$2"

  msg_normal "Installing ${target##*/}"
  if ! fs_ln_s "$target" "$link"; then
    exit 1
  fi
}

# -----------------------------------------------------------------------------
# Installer
#
# @param {string} $1 - project root path
#
install_config_vim() {
  if [ $# -ne 1 ]; then
    msg_param_error "install_config_vim" "$@"
    exit 1
  fi

  local root="$1"

  local src="${root}/config/vim"
  local dst="${HOME}/.vim"

  if ! fs_mkdir "$dst"; then
    exit 1
  fi

  install_config_vim_symlink "${src}/vimrc"      "${dst}/vimrc"
  install_config_vim_symlink "${src}/plugrc.vim" "${dst}/plugrc.vim"
}

# -----------------------------------------------------------------------------
# Driver
#
install_config_vim_driver() {
  local root
  root="$(realpath "$(dirname "$(realpath "$0")")/../../../")"

  . "${root}/script/lib/fs"
  . "${root}/script/lib/list"
  . "${root}/script/lib/msg"

  install_config_vim "$root"
}

if [ "${0##*/}" = "vim" ]; then
  install_config_vim_driver
fi
